version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
           - RAILS_ENV: 'test'

      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_DB: pictogram_test
          MYSQL_PASSWORD: ""

    working_directory: ~/pictogram

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: mv config/database.ci.yml config/database.yml

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:schema:load RAILS_ENV=test

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec
